# Generated by Django 4.0.2 on 2022-04-18 12:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/banner/', validators=[users.models.validate_image]),
        ),
    ]
