# Generated by Django 4.0.2 on 2022-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
