# Generated by Django 4.0.2 on 2022-04-29 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nba', '0002_game_away_team_name_game_home_team_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='gamedetail',
            options={'verbose_name': 'game_detail', 'verbose_name_plural': 'game_details'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'ranking', 'verbose_name_plural': 'rankings'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'season', 'verbose_name_plural': 'seasons'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('game_status', models.CharField(max_length=200)),
                ('est_date', models.DateField()),
                ('home_team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pts_home', models.FloatField(blank=True, null=True)),
                ('fg_pct_home', models.FloatField(blank=True, null=True)),
                ('ft_pct_home', models.FloatField(blank=True, null=True)),
                ('fg3_pct_home', models.FloatField(blank=True, null=True)),
                ('ast_home', models.FloatField(blank=True, null=True)),
                ('reb_home', models.FloatField(blank=True, null=True)),
                ('away_team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pts_away', models.FloatField(blank=True, null=True)),
                ('fg_pct_away', models.FloatField(blank=True, null=True)),
                ('ft_pct_away', models.FloatField(blank=True, null=True)),
                ('fg3_pct_away', models.FloatField(blank=True, null=True)),
                ('ast_away', models.FloatField(blank=True, null=True)),
                ('reb_away', models.FloatField(blank=True, null=True)),
                ('home_team_win', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_away_team', to='nba.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_home_team', to='nba.team')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nba.season')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'simulation',
                'verbose_name_plural': 'simulations',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('game_status', models.CharField(max_length=200)),
                ('est_date', models.DateField()),
                ('home_team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pts_home', models.FloatField(blank=True, null=True)),
                ('fg_pct_home', models.FloatField(blank=True, null=True)),
                ('ft_pct_home', models.FloatField(blank=True, null=True)),
                ('fg3_pct_home', models.FloatField(blank=True, null=True)),
                ('ast_home', models.FloatField(blank=True, null=True)),
                ('reb_home', models.FloatField(blank=True, null=True)),
                ('away_team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pts_away', models.FloatField(blank=True, null=True)),
                ('fg_pct_away', models.FloatField(blank=True, null=True)),
                ('ft_pct_away', models.FloatField(blank=True, null=True)),
                ('fg3_pct_away', models.FloatField(blank=True, null=True)),
                ('ast_away', models.FloatField(blank=True, null=True)),
                ('reb_away', models.FloatField(blank=True, null=True)),
                ('home_team_win', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pred_away_team', to='nba.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pred_home_team', to='nba.team')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nba.season')),
            ],
            options={
                'verbose_name': 'prediction',
                'verbose_name_plural': 'predictions',
            },
        ),
    ]
