# Generated by Django 4.0.2 on 2022-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_alter_game_options_alter_gamedetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gp_rank',
            field=models.FloatField(),
        ),
    ]
