# Generated by Django 4.0.2 on 2022-05-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_alter_player_gp_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
